rear_state:
    type: rear_drive_state_controller/RearDriveStateController

rear_command:
    type: rear_drive_command_controller/RearDriveCommandController

front_state:
    type: front_steering_state_controller/FrontSteeringStateController

front_command:
    type: front_steering_command_controller/FrontSteeringCommandController